import "./globals.css";
import connectDB from "../config/db";
import React from "react";
import Header from "./_components/Header";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Deepseek",
  description: "Generated by create next app",
};

// connectDB();
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={` antialiased bg-gray-800 dotted-background`}>
          <Header />
          <div className="max-w-5xl mx-auto p-3">{children}</div>
        </body>
      </ClerkProvider>
    </html>
  );
}
